version: "3.9"
services:
  php:
    build:
      context: ..
      dockerfile: docker/php/Dockerfile
    volumes:
      - ../:/var/www/app
    env_file:
      - ../env/.env.dev
    depends_on:
      - db
      - redis

  nginx:
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ../:/var/www/app
    ports:
      - "8080:80"
    depends_on:
      - php

  db:
    image: mysql:8.4
    env_file:
      - ../env/.env.dev
    volumes:
      - db_data:/var/lib/mysql
      - ../docker/db/init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  redis:
    image: redis:7

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"

volumes:
  db_data:
