version: "3.9"
services:
  php:
    build:
      context: ..
    env_file:
      - ../env/.env.prod

  nginx:
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
    depends_on: [php]
    ports:
      - "80:80"

  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7

volumes:
  db_data:
