version: "3.9"
services:
  php:
    build:
      context: ..
      dockerfile: docker/php/Dockerfile
    volumes:
      - ../:/var/www/app
    env_file:
      - ../env/.env.dev
    depends_on:
      - db
      - redis

  nginx:
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ../:/var/www/app
      - ../tls/${DOMAIN_BASE:-dev.local.test}:/etc/nginx/certs:ro
    ports:
      - "443:443"
      - "8080:80"   # optional: keep http for quick checks
    depends_on:
      - php

  db:
    image: mysql:8.4
    env_file:
      - ../env/.env.dev
    volumes:
      - db_data:/var/lib/mysql
      - ../docker/db/init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  redis:
    image: redis:7

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"

  adminer:
    image: adminer:latest
    depends_on:
      - db
    environment:
      # optional: set a theme, e.g. "pepa-linha"
      # ADMINER_DESIGN: pepa-linha
      # ADMINER_DEFAULT_SERVER lets Adminer prefill the server host
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8081:8080"

volumes:
  db_data:
